### ISSUE TITLE
question about primitive

### ISSUE THREAD

**Issue by ncou** [juliangut/slim-routing#14]
Hi,

nice piece of code. Just a question, reading the code i don't understand why in the file : 
https://github.com/juliangut/slim-routing/blob/master/src/Transformer/AbstractTransformer.php#L61

You don't use a cast like `(bool) $parameter;` instead of searching for 'true' and '1', I think the cast will do the same thing. I am missing something ?

Keepup the good work.

**Comment by juliangut** [comment]
Hello @ncou 

You have to consider how this feature is meant to be used, it will transform Route parameters collected from URL path. That said if we define a parameter as bool we must take care of string to boolean conversion within PHP itself

While casting "truthly" values into boolean like 'true' and '1' will return boolean true, when casting "falsy" values we encounter that anything other than '0' will be cast into boolean true!! I was considering accepting other truthly and falsy values such as 'yes', 'on', 'no' and 'off' but I've not yet had time to included them

Considering that have a look at this example:

```
php > var_dump((bool) 'true');      
php shell code:1:                   
bool(true)                          
php > var_dump((bool) '1');         
php shell code:1:
bool(true)
php > var_dump((bool) 'on');
php shell code:1:
bool(true)

php > var_dump((bool) 'false');
php shell code:1:
bool(true)
php > var_dump((bool) '0');
php shell code:1:
bool(false)
php > var_dump((bool) 'off');
php shell code:1:
bool(true)
```

**Comment by ncou** [comment]
Thank you I was not thinking about values like "on" or "off".
Thanks for your explanations. I will close the ticket.

PS : I will perhaps open other tickets, I am looking at the code to understand the magic behind all this and i will perhaps have some other silly questions (I am trying to do a microframework so i am looking at a bunch of repo) is that a problem ?

**Comment by juliangut** [comment]
Not at all, you might even find some bugs or improvement points

**Comment by ncou** [comment]
Thank you.
