### ISSUE TITLE
Container into middleware

### ISSUE THREAD

**Issue by Qumo38** [juliangut/slim-routing#17]
Hi,
how I can pass a container into middleware?

**Comment by juliangut** [comment]
Hello

You should never pass a container anywhere but the dependencies you're really going to use
Define your middleware in the container and then "get" it from it. If you find trouble defining your middleware in the container consider using another more advance (feature packed) PSR11 container other than Slim's default, for example PHPDI or Symfony's

**Comment by Qumo38** [comment]
Thank you!
