### ISSUE TITLE
Slim 4

### ISSUE THREAD

**Issue by Huholoman** [juliangut/slim-routing#18]
Hello,
as there is already Slim 4-beta, will be here update for this upcomming version?

Cheers

**Comment by juliangut** [comment]
Thanks for stepping by and ask

it sure will be, I've been planning to update to V4 for some time now but I still have to buy some time to do it

I'll keep this issue open to report back

**Comment by juliangut** [comment]
Slim4 has already been release, I should definitely find some time to update this library!!

Anyone want to lend a hand?

**Comment by juliangut** [comment]
@Huholoman I've just updated the library on brach 2.x for Slim ^4.1

I'm currently testing it in a private project and looks it's working properly. I'll still make few more test in the upcoming days before releasing a new version

Could you please make some tests on your own? mind about the changes in configuration and route registering

**Comment by juliangut** [comment]
I've just made the last changes to support Slim ^4.2 and the package is ready to be shipped shortly

**Comment by juliangut** [comment]
Released [version 2.0](https://github.com/juliangut/slim-routing/releases/tag/2.0) with support for Slim ^4.2
