### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by mbolli** [juliangut/slim-routing#21]
Currently, composer.jsoon lists `^7.1` as compatible PHP versions.

Question 1: Is it necessary at all to specify a PHP version in this project, as the compatible version is basically given by what version of Slim you support (Slim 3 for slim-routing 1.x, Slim 4 for slim-routing 2.x).

Question 2: Would you be open for a pull request for slim-routing 1.x to ensure PHP 8 compatibilty?

**Comment by juliangut** [comment]
Hello @mbolli 

First of all I got to say I'm working on a new release (2.5 maybe 3?) to support of PHP8's attributes (among other things) and remove docblock annotations, will make slim 4.7 the minimum requirement

In general defining PHP version is actually quite necessary, this library could be using some PHP capabilities not supported by PHP versions supported by Slim. For example, the aforementioned attributes makes it absolutely necessary to have PHP8 as the minimum requirement even when slim 4.7 supports ^7.2

About your second question, PRs are always welcomed, there is a 1.x branch for version 1 though it haven't had much attention really

**Comment by mbolli** [comment]
Fixed with #22
