### ISSUE TITLE
Checking for duplicated paths

### ISSUE THREAD

**Issue by kandeefloss** [juliangut/slim-routing#9]
Hi.
https://github.com/juliangut/slim-routing/blob/7a97784d09e3a9d335dc2713d48c22e83db421fb/src/Route/Resolver.php#L228
This pattern matches way too much and strips too many segments.
In consequence route path `/lorem/{ipsum:\d+}/dolor/{sit:\d+}/amet` is considered as a duplicate for `/lorem/{\d+}/amet`.

**Comment by juliangut** [comment]
You're right that regex and others were matching more than originally intended

I've updated pattern variables matching and route duplication detection to be more precise, try it and let me know

**Comment by kandeefloss** [comment]
Hi. It works like a charm now. Thanks.
